### ISSUE TITLE
Add version-increment option to increment-version-with-git

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#27]
**Is your feature request related to a problem? Please describe.**
Sometime for some reasons (most of time bad reasons), we don't want to follow the pattern you propose for determines the increment of the version.

**Describe the solution you'd like**
Add the same option (--version-increment) as in increment-version command to the increment-version-with-git command.

**Describe alternatives you've considered**
An other and maybe better option is to allow user to override your switch to make it match they desiderata.
```
return type.ToLower() switch
{
    "feat" => VersionIncrement.Minor,
    "fix" => VersionIncrement.Patch,
    "build" => VersionIncrement.Patch,
    "config" => VersionIncrement.Patch,
    "docs" => VersionIncrement.Patch,
    "perf" => VersionIncrement.Patch,
    "refactor" => VersionIncrement.Patch,
    "resolve" => VersionIncrement.Patch,
    "style" => VersionIncrement.Patch,
    "test" => VersionIncrement.Patch,
    "ci" => VersionIncrement.Patch,
    _ => VersionIncrement.Unknown
};
```
Also include `#breaking`.

**Comment by cbcrouse** [comment]
Hi @0nary, thanks for your interest in the tool. It is my understanding that you like the idea of the automatic versioning with the git commit but would like to override the determined version on demand. I will look into supporting this.

**Comment by 0nary** [comment]
@cbcrouse
Yes, it will be perfect.
