### ISSUE TITLE
Didn't work on ubuntu(-latest)

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#28]
**Describe the bug**
The command  `dotnet-version increment-version-with-git` throw exception when run on ubuntu (but work fine on windows)

**To Reproduce**
I test it on a test project so here is the version hoe failed: 
[0c5ee10fcd05c7a009a441ce3faccfa3c798f153](https://github.com/0nary/Test/blob/0c5ee10fcd05c7a009a441ce3faccfa3c798f153/.github/workflows/versioning.yml)

**Expected behavior**
I'm not sure if the command needs/must work on other support than windows, but if is not the case specify it, is a good idea.

**Comment by cbcrouse** [comment]
This is known and is not related to Versioning.NET itself, but to LibGit2Sharp which is the library this code depends on for communicating with Git. If you look in the bin directory under the runtimes folder, you will see which runtimes are supported currently. It would be good to mention this in the Wiki.

**Comment by cbcrouse** [comment]
The [documentation](https://github.com/cbcrouse/Versioning.NET/wiki/Configuring-CI-CD#troubleshooting) has been updated to call out supported operating systems.
