### ISSUE TITLE
Don't force semver tag to start with a 'v'

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#30]
**Is your feature request related to a problem? Please describe.**
In the majority of the project I can see the semver tag doesn't start with a v, and I see no good reason why they must.
When I work on an open project if I want to use your auto-versioning tool I must ask to start the semver tag with a v, only for the use of your tool. 

**Describe the solution you'd like**
Just check if the tag matches the regex `^((\d+)\.(\d+)\.(\d+))`, and don't force the use of 'v'.

**Comment by cbcrouse** [comment]
This 'v' is strictly for the git tag, not for the project file versions. What exactly is causing an issue for you?

**Comment by JBBianchi** [comment]
@cbcrouse because this is an opinionated choice you impose. The best would be to let the user choose it's own format.

For instance, take the [ASPNetCore](https://github.com/dotnet/core/releases) repo, the tags are in the format of `.NET x.x.x`, in [OData](https://github.com/OData/AspNetCoreOData/releases) it's `ASP.NET Core OData x.x.x`

I'd suggest to either add a argument like `--format-tag 'My Tag v##Version##'` (or any kind of templating synthax) or add to arguments like `--tag-prefix` and `--tag-suffix` e.g.: `--tag-prefix 'v' --tag-suffix '-alpha'`

**Comment by cbcrouse** [comment]
Thanks for the additional clarification @JBBianchi. The [ASPNetCore](https://github.com/dotnet/core/releases) link you mentioned, the tag is not actually `.NET x.x.x`, but rather `vX.X.X-suffix`, e.g., `v7.0.0-rc.1`. The same is similar for the OData link you shared. The values you mentioned are simply the release title they are using which can be typed in manually.

![image](https://user-images.githubusercontent.com/6248703/192114024-be327b07-f740-46cc-bbfb-f3092bd6ab9b.png)

![image](https://user-images.githubusercontent.com/6248703/192114006-f0095c57-d783-4c0b-a1a1-bb805c661d9c.png)

However, I do see the opportunity here for increased flexibility with the tool and will spend some time considering the best approach for this. I would like to keep this tag as close to semantic versioning standards as possible.

One of the main reasons for keeping the 'v' in the name is to distinguish between various tags in a git tree that may match the format but not be a valid version. For example, take a date `10.31.2020` which matches the version syntax of `x.x.x` but is not a version. Build numbers can also be added as git tags from automated process in CI pipelines. This tool modifies the version in the code and makes commits to the branch, so it's important to be as careful as we can to not make an incorrect change. It's fair to say that a user should read the documentation of the tool and understand how various tag formats could disrupt their ability to automatically version their code properly with this tool, but it's a better practice to protect them from themselves by having a more robust tagging strategy.

To be clear, the above statement does not mean that the 'v' should stick around, but mainly to describe some issues that have come up in the past and the reason for its existence.

**Comment by JBBianchi** [comment]
Awsome, thanks!
