### ISSUE TITLE
Versioning.NET remove user indentation and spacing in csproj files.

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#32]
**Describe the bug**
Versioning.NET remove user indentation and spacing in csproj files.

**Expected behavior**
Only change the value of the Version/VersionPrefix.

**Screenshots**
![image](https://user-images.githubusercontent.com/102674985/191539991-e7cdd657-5f5d-43ea-ab6a-272706e9fb5a.png)

More can be seen at https://github.com/0nary/synapse/commit/ce5f268e9a5fcc19b74d971e62a679dbc1efec27.

**Comment by cbcrouse** [comment]
Problem is unfortunately worse after 'fixing' it. Now everything is being shrunk to 1 line due to when the document was loaded versus when the preserve space configuration was set.

![image](https://user-images.githubusercontent.com/6248703/197441693-100ae281-08dd-4f14-ba8a-a9bd6b445d46.png)
