### ISSUE TITLE
Wiki : Install Versioning.NET Tool with version specified

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#41]
**Is your feature request related to a problem? Please describe.**
When you make a breaking change, it might break the workflows, how use your versioning tool.

**Describe the solution you'd like**
It might be a good idea to encourage the user to always specify the version they wish to install.
And so I think is a good idea to write it in [the wiki section for Install Versioning.NET Tool](https://github.com/cbcrouse/Versioning.NET/wiki/Configuring-CI-CD#install-versioningnet-tool).

**Comment by cbcrouse** [comment]
This has been mentioned explicitly in the wiki. Thanks!
