### ISSUE TITLE
Wiki : Configuring CI CD is outdated

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#42]
**Is your feature request related to a problem? Please describe.**
I think [the Configuring CI CD Run Command part](https://github.com/cbcrouse/Versioning.NET/wiki/Configuring-CI-CD#run-command) of your wiki is outdated

**Describe the solution you'd like**
Does 
```
dotnet-version increment-version-with-git -g "$(Build.SourcesDirectory)" -a "devops@versioning.net" -b "$(Build.SourceBranchName)"
```
should not be 

```
dotnet-version increment-version-with-git -g "$(Build.SourcesDirectory)" -a "devops@versioning.net" -b "$(Build.SourceBranchName)" -v "$(VERSION_INCREMENT)"
```

**Comment by cbcrouse** [comment]
Thanks, the documentation has been updated.
