### ISSUE TITLE
Unexpected `Increment 'Unknown'`

### ISSUE THREAD

**Issue by JBBianchi** [cbcrouse/Versioning.NET#43]
**Describe the bug**
On one specific project, when merging branches to the main one, the tools doesn't see to be able to find the increment to apply. This doesn't seem to happen when committing directly to main.
This happens since an (unrelated) build job failed in a pipeline ...

**To Reproduce**
Steps to reproduce the behavior (**not sure**):
1. Update action to use `increment-version-with-git-hints` : https://github.com/neuroglia-io/framework/commit/aa5af595e9a1b30fe09d473a52c002d7a811922d
2. Create a branch with erroneous step (moved sln file) after the versioning happens (tag with no release ?) : https://github.com/neuroglia-io/framework/actions/runs/3336738423/jobs/5522252376 
3. The previous step created an increment : https://github.com/neuroglia-io/framework/commit/e9717e5c81fa24cd7700ca8e53cdeaa01207fa51
4. Fix the actions (fixed sln path): https://github.com/neuroglia-io/framework/commit/97966fd88676c0f77b83185b39af2e90d0a8580e / https://github.com/neuroglia-io/framework/commit/30989c38ee290e54ebc9fcdb71bd07fe2b61d077 / https://github.com/neuroglia-io/framework/commit/db1e3c860818c559671a0390a787f9219d48d19e
5. Manually create a new release linked to the tag created by Versioning.NET : https://github.com/neuroglia-io/framework/releases/tag/v2.0.4
6. Create a branch and merge it to trigger a new action instance : https://github.com/neuroglia-io/framework/commit/75ebc8684d850cc5e9ee2e3e1583f5959b0cbf2d
7. Increment 'Unknown' happens
8. Commit to main directly : https://github.com/neuroglia-io/framework/commit/04774a915c60b056b14413f9b6f9baee7dcade44
9. Versioning works ...
10. Create a branch and merge, versioning doesn't work ...

See https://github.com/neuroglia-io/framework/commits/main?after=a86a7ab0487d31a15d00a1a28418a08e6b8b88b2+0&branch=main&qualified_name=refs%2Fheads%2Fmain
![history](https://user-images.githubusercontent.com/72747835/199505521-fcaf5893-2bf5-4818-bb01-1519324dad40.png)

I don't get what is happening and how to fix it, any pointers ?

**Comment by JBBianchi** [comment]
I think it's because of the `.` in the hints, can it be ?

**Comment by JBBianchi** [comment]
I think it is, here are two tests:

https://github.com/neuroglia-io/TestCICD/commits/main 
- 8ad3c63 >> https://github.com/neuroglia-io/TestCICD/actions/runs/3378162077/jobs/5608001793 >> Increment 'Unknown'

- 16a7526 >> https://github.com/neuroglia-io/TestCICD/actions/runs/3378181794/jobs/5608048354 >> Incremented assembly versions by Patch.

**Comment by cbcrouse** [comment]
Hi @JBBianchi - thanks again for submitting your issue. I think you also found the reason for failure 👍. After looking at the regex pattern, we can clearly see that the commit with the dot is not being detected.

![image](https://user-images.githubusercontent.com/6248703/199639435-619601d4-619c-497d-9d12-f3b89eb67807.png)

Should be easy enough to fix, good catch!
